//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filtration.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filtration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_01 {
            get {
                return ResourceManager.GetStream("AlertSound_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_02 {
            get {
                return ResourceManager.GetStream("AlertSound_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_03 {
            get {
                return ResourceManager.GetStream("AlertSound_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_04 {
            get {
                return ResourceManager.GetStream("AlertSound_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_05 {
            get {
                return ResourceManager.GetStream("AlertSound_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_06 {
            get {
                return ResourceManager.GetStream("AlertSound_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_07 {
            get {
                return ResourceManager.GetStream("AlertSound_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_08 {
            get {
                return ResourceManager.GetStream("AlertSound_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_09 {
            get {
                return ResourceManager.GetStream("AlertSound_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_10 {
            get {
                return ResourceManager.GetStream("AlertSound_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_11 {
            get {
                return ResourceManager.GetStream("AlertSound_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_12 {
            get {
                return ResourceManager.GetStream("AlertSound_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_13 {
            get {
                return ResourceManager.GetStream("AlertSound_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_14 {
            get {
                return ResourceManager.GetStream("AlertSound_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_15 {
            get {
                return ResourceManager.GetStream("AlertSound_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream AlertSound_16 {
            get {
                return ResourceManager.GetStream("AlertSound_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Area Damage
        ///Armour
        ///Attack Damage
        ///Attack Damage while Dual Wielding
        ///Attack Damage while holding a Shield
        ///Aura Effect
        ///Axe and Sword Damage
        ///Bow Damage
        ///Brand Damage
        ///Chance to Block Attack Damage
        ///Chance to Block Spell Damage
        ///Channelling Skill Damage
        ///Chaos Damage
        ///Chaos Damage over Time
        ///Chaos Resistance
        ///Cold Damage
        ///Cold Damage over Time
        ///Cold Resistance
        ///Critical Chance
        ///Curse Effect
        ///Dagger and Claw Damage
        ///Damage over Time
        ///Damage while you have a Herald
        ///Damage with Two Handed Weapons
        ///Effect of [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string EnchantmentPassiveNode {
            get {
                return ResourceManager.GetString("EnchantmentPassiveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armageddon Brand Attached Target Fire Penetration 1
        ///Armageddon Brand Attached Target Fire Penetration 2
        ///Armageddon Brand Repeat Frequency 1
        ///Armageddon Brand Repeat Frequency 2
        ///Absolution Cast Speed 1
        ///Absolution Cast Speed 2
        ///Absolution Duration 1
        ///Absolution Duration 2
        ///Absolution Minion Area of Effect 1
        ///Absolution Minion Area of Effect 2
        ///Alchemist&apos;s Mark Curse Effect 1
        ///Alchemist&apos;s Mark Curse Effect 2
        ///Ambush Cooldown Recovery 1
        ///Ambush Cooldown Recovery 2
        ///Ambush Critical Strike Multiplier 1
        ///Ambus [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Enchantments {
            get {
                return ResourceManager.GetString("Enchantments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Fontin_SmallCaps {
            get {
                object obj = ResourceManager.GetObject("Fontin_SmallCaps", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap groundtile {
            get {
                object obj = ResourceManager.GetObject("groundtile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shaper
        ///Elder
        ///Crusader
        ///Hunter
        ///Redeemer
        ///Warlord
        ///None.
        /// </summary>
        internal static string Influences {
            get {
                return ResourceManager.GetString("Influences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A Chilling Wind
        ///A Dab of Ink
        ///A Dusty Memory
        ///A Familiar Call
        ///A Fate Worse Than Death
        ///A Modest Request
        ///A Mother&apos;s Parting Gift
        ///A Note in the Wind
        ///A Sea of Blue
        ///A Stone Perfected
        ///Abandoned Wealth
        ///Aberrant Fossil
        ///Abrasive Catalyst
        ///Absolution
        ///Abyssal Axe
        ///Abyssal Delirium Orb
        ///Abyssal Incubator
        ///Abyssal Sceptre
        ///Academy Map
        ///Accelerating Catalyst
        ///Acclimatisation
        ///Accumulator Wand
        ///Acid Caverns Map
        ///Added Chaos Damage Support
        ///Added Cold Damage Support
        ///Added Fire Damage Support
        ///Added Lightning Da [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ItemBaseTypes {
            get {
                return ResourceManager.GetString("ItemBaseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abyss Jewel
        ///Active Skill Gems
        ///Amulets
        ///Atlas Upgrade Item
        ///Axes
        ///Belts
        ///Blueprint
        ///Body Armours
        ///Boots
        ///Bows
        ///Breachstone
        ///Claws
        ///Contract
        ///Currency
        ///Daggers
        ///Delve Socketable Currency
        ///Delve Stackable Socketable Currency
        ///Divination Card
        ///Fishing Rods
        ///Flasks
        ///Gems
        ///Gloves
        ///Heist Brooch
        ///Heist Cloak
        ///Heist Gear
        ///Heist Target
        ///Heist Tool
        ///Helmets
        ///Hybrid Flasks
        ///Incubator
        ///Incursion Item
        ///Jewel
        ///Labyrinth Item
        ///Labyrinth Map Item
        ///Labyrinth Trinket
        ///Leaguestones
        ///Life Flasks
        ///Logbook
        ///Maces
        ///Mana Flasks
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ItemClasses {
            get {
                return ResourceManager.GetString("ItemClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abating
        ///Abbot&apos;s
        ///Abecedarian&apos;s
        ///Abundant
        ///Acolyte&apos;s
        ///Acrobat&apos;s
        ///Acute
        ///Adaptable
        ///Adept&apos;s
        ///Adroit
        ///Affecting
        ///Aged
        ///Agile
        ///Alarmed
        ///Alchemist&apos;s
        ///Allocated
        ///Alluring
        ///Alpine
        ///Ample
        ///Analyst&apos;s
        ///Anarchist&apos;s
        ///Annealed
        ///Annest&apos;s
        ///Anointed
        ///Apparition&apos;s
        ///Apprentice&apos;s
        ///Aqua
        ///Archmage&apos;s
        ///Arcing
        ///Armadillo&apos;s
        ///Artificer&apos;s
        ///Athlete&apos;s
        ///Azure
        ///Barbed
        ///Baroness&apos;s
        ///Baron&apos;s
        ///Beatified
        ///Beetle&apos;s
        ///Behemoth&apos;s
        ///Beryl
        ///Bishop&apos;s
        ///Biting
        ///Bitter
        ///Blacksmith&apos;s
        ///Blasting
        ///Blazing
        ///Blessed
        ///Blistering
        ///Bloodthirsty
        ///Blue
        ///Blurred
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ItemMods {
            get {
                return ResourceManager.GetString("ItemMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Alchemy {
            get {
                return ResourceManager.GetStream("SH22Alchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Blessed {
            get {
                return ResourceManager.GetStream("SH22Blessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Chaos {
            get {
                return ResourceManager.GetStream("SH22Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Divine {
            get {
                return ResourceManager.GetStream("SH22Divine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Exalted {
            get {
                return ResourceManager.GetStream("SH22Exalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Fusing {
            get {
                return ResourceManager.GetStream("SH22Fusing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22General {
            get {
                return ResourceManager.GetStream("SH22General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Mirror {
            get {
                return ResourceManager.GetStream("SH22Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Regal {
            get {
                return ResourceManager.GetStream("SH22Regal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream SH22Vaal {
            get {
                return ResourceManager.GetStream("SH22Vaal", resourceCulture);
            }
        }
    }
}
